import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp,writeFile,chmod,rm } from 'node:fs/promises';
import { preflightCodex,childEnvironment } from '../../skills/assignment-review/scripts/codex-preflight.mjs';
async function fake(script,fn){const root=await mkdtemp('/private/tmp/el20-preflight-');await chmod(root,0o700);const exe=root+'/codex';await writeFile(exe,'#!/bin/sh\n'+script,{mode:0o700});try{await fn(exe,root);}finally{await rm(root,{recursive:true,force:true});}}
const help='--json --output-schema --ephemeral --ignore-user-config --ignore-rules --strict-config --skip-git-repo-check';
const script=status=>`case "$1" in --version) echo 'codex-cli 0.141.0';; exec) echo '${help}';; login) echo '${status}';; *) exit 99;; esac`;
const options=executable=>({executable,platform:'darwin',arch:'arm64',environment:{HOME:'/Users/test',PATH:'/usr/bin:/bin'}});
test('preflight reports prerequisites, never inference readiness',()=>fake(script('Logged in using ChatGPT'),async exe=>{const r=await preflightCodex(options(exe));assert.equal(r.ok,true);assert.equal(r.auth,'chatgpt');assert.equal(r.executionReady,false);assert.match(r.binarySha256,/^[a-f0-9]{64}$/);}));
for(const [status,code] of [['Not logged in','login_required'],['Logged in using an API key','auth_mode_unsupported'],['unexpected sk-syntheticNeverEchoThisSecret123456','uncertain']])test('bounded login classification '+code,()=>fake(script(status),async exe=>{const r=await preflightCodex(options(exe));assert.equal(r.code,code);assert.equal(JSON.stringify(r).includes('sk-'),false);}));
test('missing executable and unsupported platforms fail before spawn',async()=>{assert.equal((await preflightCodex(options('/no/such/codex'))).code,'codex_missing');assert.equal((await preflightCodex({...options('/no/such/codex'),platform:'linux'})).code,'unsupported');});
test('recursive child is rejected before any executable access',async()=>{assert.equal((await preflightCodex({...options('/no/such/codex'),environment:{EVIDENCELENS_CHILD:'1'}})).code,'recursive_call');});
test('untrusted executable mode and changed version are rejected',async()=>{await fake(script('Logged in using ChatGPT').replace('0.141.0','0.140.0'),async exe=>assert.equal((await preflightCodex(options(exe))).code,'codex_incompatible'));await fake(script('Logged in using ChatGPT'),async exe=>{await chmod(exe,0o777);assert.equal((await preflightCodex(options(exe))).code,'unsafe_path');});});
test('deadline reaps owned hanging preflight group',()=>fake('sleep 30',async exe=>{const at=Date.now(),r=await preflightCodex({...options(exe),timeoutMs:80});assert.equal(r.code,'timed_out');assert.ok(Date.now()-at<4500);assert.equal(r.cleanupComplete,true);}));
test('oversize output stops process without leaking text',()=>fake('while true; do echo outputflood; done',async exe=>{const r=await preflightCodex(options(exe));assert.equal(r.code,'output_limit');assert.equal(r.cleanupComplete,true);}));
test('child environment excludes credentials, proxies and parent identity',()=>{const env=childEnvironment({HOME:'/home/user',CODEX_HOME:'/home/user/codex',OPENAI_API_KEY:'secret',CODEX_THREAD_ID:'parent',HTTPS_PROXY:'secret',SHELL:'/bin/zsh'},'/private/tmp/scratch');assert.deepEqual(Object.keys(env).sort(),['CODEX_HOME','EVIDENCELENS_CHILD','HOME','LANG','PATH','TMPDIR']);assert.equal(env.EVIDENCELENS_CHILD,'1');assert.equal(env.OPENAI_API_KEY,undefined);});
