import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {randomUUID} from 'node:crypto';
import {spawnSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
import {join} from 'node:path';
import {consumeCaptured} from '../../skills/assignment-review/scripts/prompt-records.mjs';
import {beginRun,captureRun,exportLatest} from '../../skills/assignment-review/scripts/prompt-store.mjs';
import {sha256} from '../../skills/assignment-review/scripts/prompt-contract.mjs';
const cli=fileURLToPath(new URL('../../skills/assignment-review/scripts/prompt-records.mjs',import.meta.url));
async function setup(t){const root=await fs.mkdtemp('/private/tmp/el19-cli-');await fs.chmod(root,0o700);t.after(()=>fs.rm(root,{recursive:true,force:true}));const scope={stateRoot:join(root,'state'),conversationId:randomUUID(),taskId:'T-cli'};const env={PATH:process.env.PATH,CODEX_THREAD_ID:scope.conversationId,EVIDENCELENS_STATE_ROOT:scope.stateRoot};return {scope,call:(action,input={},args=[])=>spawnSync(process.execPath,[cli,action,...args],{input:JSON.stringify(input),env,cwd:'/private/tmp',encoding:'utf8',timeout:10000})};}
function snap(r){const promptText='  中文\r\n```hello```\n  ';return {schemaVersion:1,runId:r.runId,taskId:r.taskId,conversationId:r.conversationId,sequence:r.sequence,stage:'final',reviewMode:'artifact_only',currentSourceId:null,promptText,promptSha256:sha256(promptText),capturedAt:new Date().toISOString(),materials:[],limitations:[]};}
test('real CLI dispatch and repeated export are byte identical with separated metadata',async t=>{const {call}=await setup(t);const b=call('begin');assert.equal(b.status,0,b.stderr);const r=JSON.parse(b.stdout),s=snap(r);assert.equal(call('capture',{taskId:r.taskId,runId:r.runId,snapshot:s}).status,0);const sent=call('dispatch',{taskId:r.taskId,runId:r.runId},['--format=raw']);assert.equal(sent.status,0,sent.stderr);assert.equal(sent.stdout,s.promptText);const a=call('export',{taskId:r.taskId,expectedRunId:r.runId},['--format=raw']);const b2=call('export',{taskId:r.taskId,expectedRunId:r.runId},['--format=raw']);assert.equal(a.stdout,sent.stdout);assert.equal(b2.stdout,sent.stdout);assert.equal(JSON.parse(a.stderr).status,'dispatched');assert.notEqual(call('dispatch',{taskId:r.taskId,runId:r.runId}).status,0);assert.equal(call('finish',{taskId:r.taskId,runId:r.runId,status:'succeeded'}).status,0);assert.equal(JSON.parse(call('status',{taskId:r.taskId}).stdout).status,'succeeded');});
test('identity overrides and unknown fields fail with no input echoed',async t=>{const {call}=await setup(t);for(const v of [{conversationId:randomUUID()},{hidden:'DO-NOT-ECHO'}]){const r=call('begin',v);assert.equal(r.status,1);assert.ok(!r.stderr.includes('DO-NOT-ECHO'));}assert.equal(call('export').status,1);const r=spawnSync(process.execPath,['--input-type=module','-e',`await import(${JSON.stringify('file://'+cli)})`],{encoding:'utf8',timeout:10000});assert.equal(r.stdout,'');assert.equal(r.stderr,'');});
test('consumer gets saved bytes once, failure never retries and export does not call it',async t=>{const {scope}=await setup(t);const r=await beginRun(scope),s=snap(r);await captureRun(scope,r.runId,s);let calls=0;await assert.rejects(consumeCaptured(scope,r.runId,async bytes=>{calls++;assert.deepEqual(bytes,Buffer.from(s.promptText));throw Error('PRIVATE_FAILURE');}));assert.equal(calls,1);const x=await exportLatest(scope,{expectedRunId:r.runId});assert.equal(x.metadata.status,'failed');await assert.rejects(consumeCaptured(scope,r.runId,()=>{calls++;}));assert.equal(calls,1);});
