import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import { join } from 'node:path';
import { randomUUID } from 'node:crypto';
import { beginRun,captureRun,readForDispatch,finishRun,exportLatest } from '../../skills/assignment-review/scripts/prompt-store.mjs';
import {sha256} from '../../skills/assignment-review/scripts/prompt-contract.mjs';
async function fixture(t){const root=await fs.mkdtemp('/private/tmp/el19-');await fs.chmod(root,0o700);t.after(()=>fs.rm(root,{recursive:true,force:true}));return {stateRoot:join(root,'state'),conversationId:randomUUID(),taskId:'T1'};}
function snapshot(r,promptText='  example\r\n中文\n'){return {schemaVersion:1,runId:r.runId,taskId:r.taskId,conversationId:r.conversationId,sequence:r.sequence,stage:'final',reviewMode:'artifact_only',currentSourceId:null,promptText,promptSha256:sha256(promptText),capturedAt:new Date().toISOString(),materials:[],limitations:[]};}
test('immutable capture and dispatch/export bytes, latest begin beats completion',async t=>{const s=await fixture(t);const a=await beginRun(s);const x=snapshot(a);await captureRun(s,a.runId,x);await captureRun(s,a.runId,x);await assert.rejects(captureRun(s,a.runId,snapshot(a,'changed')));const sent=await readForDispatch(s,a.runId);assert.equal(sent.promptText,x.promptText);const b=await beginRun(s);await finishRun(s,a.runId,{status:'succeeded'});await assert.rejects(exportLatest(s,{expectedRunId:a.runId}),{code:'latest_mismatch'});await assert.rejects(exportLatest(s,{expectedRunId:b.runId}),{code:'uncertain'});await captureRun(s,b.runId,snapshot(b,'new'));await finishRun(s,b.runId,{status:'failed',errorCode:'uncertain'});assert.equal((await exportLatest(s,{expectedRunId:b.runId})).metadata.status,'failed');});
test('isolated tasks/conversations and lost receipt never fall back',async t=>{const s=await fixture(t);await assert.rejects(exportLatest(s,{}),{code:'no_record'});const a=await beginRun(s);await captureRun(s,a.runId,snapshot(a));const other={...s,taskId:'T2'};const b=await beginRun(other);await captureRun(other,b.runId,snapshot(b,'other'));assert.equal((await exportLatest(s,{expectedRunId:a.runId})).promptText,snapshot(a).promptText);await assert.rejects(exportLatest(s,{}),{code:'identity_required'});await assert.rejects(exportLatest({...s,conversationId:randomUUID()},{expectedRunId:a.runId}),{code:'latest_mismatch'});await assert.rejects(exportLatest({...s,taskId:undefined},{expectedRunId:a.runId}),{code:'identity_required'});});
test('failed admission retains attempted receipt and partial publication blocks reads',async t=>{const s=await fixture(t);const a=await beginRun(s);await captureRun(s,a.runId,snapshot(a));const failed=await beginRun({...s,onBoundary(name){if(name==='before_state')throw Error('injected');}});assert.equal(failed.ok,false);assert.notEqual(failed.runId,a.runId);await assert.rejects(exportLatest(s,{expectedRunId:failed.runId}),{code:'latest_mismatch'});const dirty=await beginRun({...s,onBoundary(name){if(name==='after_state')throw Error('injected');}});assert.equal(dirty.ok,false);await assert.rejects(exportLatest(s,{expectedRunId:dirty.runId}),{code:'busy'});});
test('unsafe paths, symlinks, permissions, git and evidence overlap rejected',async t=>{const s=await fixture(t);const root=s.stateRoot;await fs.mkdir(root,{mode:0o700});await fs.writeFile(join(root,'.git'),'worktree');assert.equal((await beginRun(s)).code,'unsafe_path');await fs.unlink(join(root,'.git'));await fs.chmod(root,0o755);assert.equal((await beginRun(s)).code,'unsafe_path');await fs.chmod(root,0o700);assert.equal((await beginRun({...s,evidenceRoots:[root]})).code,'unsafe_path');await fs.symlink(root,root+'-link');assert.equal((await beginRun({...s,stateRoot:root+'-link'})).code,'unsafe_path');});
test('corrupted latest never returns older snapshot',async t=>{const s=await fixture(t);const a=await beginRun(s);await captureRun(s,a.runId,snapshot(a));const p=join(s.stateRoot,sha256(s.conversationId),sha256(s.taskId),a.runId+'.snapshot.json');await fs.writeFile(p,'{}');await assert.rejects(exportLatest(s,{expectedRunId:a.runId}),{code:'corrupt_record'});});
